-- 初始化服务数据
-- 清空现有数据（可选）
-- DELETE FROM ServiceItems;

-- 插入示例服务数据
INSERT INTO ServiceItems (id, name, description, category, price, originalPrice, imageUrl, formConfig, status, sort) VALUES
(1, '专业陪诊套餐', '专业陪诊师全程陪同就医，提供挂号、排队、取药等服务', '医院陪诊', 299.00, 399.00, '/images/service-escort.jpg', '{"fields":[{"name":"patientName","label":"就诊人姓名","type":"text","required":true,"placeholder":"请输入就诊人姓名"},{"name":"patientPhone","label":"联系电话","type":"text","required":true,"placeholder":"请输入联系电话"},{"name":"hospitalName","label":"医院名称","type":"text","required":true,"placeholder":"请输入医院名称"},{"name":"department","label":"科室","type":"text","required":true,"placeholder":"请输入科室名称"},{"name":"appointmentDate","label":"预约日期","type":"date","required":true},{"name":"symptoms","label":"症状描述","type":"textarea","required":false,"placeholder":"请描述主要症状（选填）"}]}', 1, 1),

(2, '上门护理服务', '专业护士上门提供护理服务，包括伤口护理、换药、输液等', '专业护理', 199.00, 299.00, '/images/service-nursing.jpg', '{"fields":[{"name":"patientName","label":"患者姓名","type":"text","required":true,"placeholder":"请输入患者姓名"},{"name":"patientPhone","label":"联系电话","type":"text","required":true,"placeholder":"请输入联系电话"},{"name":"patientAge","label":"患者年龄","type":"number","required":true,"placeholder":"请输入患者年龄"},{"name":"careType","label":"护理类型","type":"select","required":true,"options":[{"label":"伤口护理","value":"wound_care"},{"label":"换药","value":"dressing_change"},{"label":"输液","value":"infusion"},{"label":"其他","value":"other"}]},{"name":"address","label":"服务地址","type":"textarea","required":true,"placeholder":"请输入详细的服务地址"},{"name":"specialNeeds","label":"特殊需求","type":"textarea","required":false,"placeholder":"请描述特殊需求（选填）"}]}', 1, 2),

(3, '生活照护服务', '专业护工提供日常生活照料，包括饮食、清洁、陪伴等服务', '生活照护', 150.00, 200.00, '/images/service-care.jpg', '{"fields":[{"name":"patientName","label":"患者姓名","type":"text","required":true,"placeholder":"请输入患者姓名"},{"name":"patientPhone","label":"联系电话","type":"text","required":true,"placeholder":"请输入联系电话"},{"name":"patientAge","label":"患者年龄","type":"number","required":true,"placeholder":"请输入患者年龄"},{"name":"careDuration","label":"服务时长","type":"select","required":true,"options":[{"label":"4小时","value":"4"},{"label":"8小时","value":"8"},{"label":"12小时","value":"12"},{"label":"24小时","value":"24"}]},{"name":"careItems","label":"服务项目","type":"radio","required":true,"options":[{"label":"饮食照料","value":"diet_care"},{"label":"清洁护理","value":"cleaning_care"},{"label":"陪伴服务","value":"companionship"},{"label":"全项服务","value":"full_service"}]},{"name":"address","label":"服务地址","type":"textarea","required":true,"placeholder":"请输入详细的服务地址"}]}', 1, 3),

(4, '康复护理服务', '专业康复师提供术后康复、理疗、功能训练等服务', '专业护理', 250.00, 350.00, '/images/service-rehab.jpg', '{"fields":[{"name":"patientName","label":"患者姓名","type":"text","required":true,"placeholder":"请输入患者姓名"},{"name":"patientPhone","label":"联系电话","type":"text","required":true,"placeholder":"请输入联系电话"},{"name":"injuryType","label":"损伤类型","type":"select","required":true,"options":[{"label":"骨科术后","value":"orthopedic"},{"label":"神经损伤","value":"neurological"},{"label":"运动损伤","value":"sports"},{"label":"其他","value":"other"}]},{"name":"injuryLocation","label":"损伤部位","type":"text","required":true,"placeholder":"请输入损伤部位"},{"name":"surgeryDate","label":"手术日期","type":"date","required":false},{"name":"currentCondition","label":"当前状况","type":"textarea","required":true,"placeholder":"请描述当前身体状况"}]}', 1, 4),

(5, '健康体检套餐A', '基础健康体检，包含血常规、尿常规、心电图等检查项目', '体检', 299.00, 399.00, '/images/health-check-a.jpg', '{"fields":[{"name":"patientName","label":"体检人姓名","type":"text","required":true,"placeholder":"请输入体检人姓名"},{"name":"patientPhone","label":"联系电话","type":"text","required":true,"placeholder":"请输入联系电话"},{"name":"patientIdCard","label":"身份证号","type":"text","required":true,"placeholder":"请输入身份证号"},{"name":"patientBirthday","label":"出生日期","type":"date","required":true},{"name":"patientGender","label":"性别","type":"radio","required":true,"options":[{"label":"男","value":"male"},{"label":"女","value":"female"}]},{"name":"emergencyContact","label":"紧急联系人","type":"text","required":true,"placeholder":"请输入紧急联系人姓名"},{"name":"emergencyPhone","label":"紧急联系电话","type":"text","required":true,"placeholder":"请输入紧急联系电话"}]}', 1, 5),

(6, '健康体检套餐B', '全面健康体检，包含血常规、尿常规、心电图、B超等检查项目', '体检', 599.00, 799.00, '/images/health-check-b.jpg', '{"fields":[{"name":"patientName","label":"体检人姓名","type":"text","required":true,"placeholder":"请输入体检人姓名"},{"name":"patientPhone","label":"联系电话","type":"text","required":true,"placeholder":"请输入联系电话"},{"name":"patientIdCard","label":"身份证号","type":"text","required":true,"placeholder":"请输入身份证号"},{"name":"patientBirthday","label":"出生日期","type":"date","required":true},{"name":"patientGender","label":"性别","type":"radio","required":true,"options":[{"label":"男","value":"male"},{"label":"女","value":"female"}]},{"name":"medicalHistory","label":"既往病史","type":"textarea","required":false,"placeholder":"请描述既往病史（选填）"},{"name":"allergies","label":"过敏史","type":"textarea","required":false,"placeholder":"请描述过敏史（选填）"},{"name":"emergencyContact","label":"紧急联系人","type":"text","required":true,"placeholder":"请输入紧急联系人姓名"},{"name":"emergencyPhone","label":"紧急联系电话","type":"text","required":true,"placeholder":"请输入紧急联系电话"}]}', 1, 6),

(7, '心理咨询服务', '专业心理咨询，一对一心理疏导，帮助解决心理问题', '心理咨询', 200.00, 300.00, '/images/psychology.jpg', '{"fields":[{"name":"patientName","label":"咨询者姓名","type":"text","required":true,"placeholder":"请输入咨询者姓名"},{"name":"patientPhone","label":"联系电话","type":"text","required":true,"placeholder":"请输入联系电话"},{"name":"patientAge","label":"年龄","type":"number","required":true,"placeholder":"请输入年龄"},{"name":"consultationType","label":"咨询类型","type":"select","required":true,"options":[{"label":"情感咨询","value":"emotion"},{"label":"工作压力","value":"work_pressure"},{"label":"家庭关系","value":"family"},{"label":"学业问题","value":"academic"},{"label":"其他","value":"other"}]},{"name":"problemDescription","label":"问题描述","type":"textarea","required":true,"placeholder":"请详细描述您遇到的问题"},{"name":"preferredTime","label":"期望咨询时间","type":"text","required":true,"placeholder":"请输入期望的咨询时间"}]}', 1, 7),

(8, '营养师咨询', '专业营养师一对一咨询，制定个性化营养方案', '营养咨询', 150.00, 200.00, '/images/nutrition.jpg', '{"fields":[{"name":"patientName","label":"咨询者姓名","type":"text","required":true,"placeholder":"请输入咨询者姓名"},{"name":"patientPhone","label":"联系电话","type":"text","required":true,"placeholder":"请输入联系电话"},{"name":"patientHeight","label":"身高(cm)","type":"number","required":true,"placeholder":"请输入身高"},{"name":"patientWeight","label":"体重(kg)","type":"number","required":true,"placeholder":"请输入体重"},{"name":"nutritionGoal","label":"营养目标","type":"select","required":true,"options":[{"label":"减重","value":"weight_loss"},{"label":"增重","value":"weight_gain"},{"label":"健康管理","value":"health_management"},{"label":"疾病调理","value":"disease_management"}]},{"name":"medicalHistory","label":"疾病史","type":"textarea","required":false,"placeholder":"请描述相关疾病史（选填）"},{"name":"dietaryRestrictions","label":"饮食禁忌","type":"textarea","required":false,"placeholder":"请描述饮食禁忌（选填）"}]}', 1, 8)

ON DUPLICATE KEY UPDATE
name = VALUES(name),
description = VALUES(description),
category = VALUES(category),
price = VALUES(price),
originalPrice = VALUES(originalPrice),
imageUrl = VALUES(imageUrl),
formConfig = VALUES(formConfig),
status = VALUES(status),
sort = VALUES(sort),
updatedAt = CURRENT_TIMESTAMP; 